path: task32
final_goal: 32_4.task
common:
  trainer:
    nsteps: 500
stages:
  - config: stage1_wind.yaml 
  - config: away.yaml
    modifier:
      scene:
        goal: 32_1.task 
  - config: stage2_wind.yaml
    modifier:
      scene:
        goal: 32_2.task 
  - config: away.yaml
    modifier:
      scene:
        goal: 32_2.task 
  - config: stage3_wind.yaml
    modifier:
      scene:
        goal: 32_3.task 
  - config: away.yaml
    modifier:
      scene:
        goal: 32_3.task 
  - config: stage4.yaml
    modifier:
      scene:
        goal: 32_4.task
  - config: away.yaml
    modifier:
      scene:
        goal: 32_4.task 