scene: 
  path: wind_gripper.yml
  Tool:
    tool_name: Gripper
    qpos: [0.7, 0.1, 0.3, 0., 1.57, 0., 0.00]
    size: (0.03, 0.05, 0.03)
saver:
  path: examples/output/pickup_rope
optim:
  lr: 0.02
trainer:
  nsteps: 300
prog: 
  code: pickup_rope()
  horizon: 40