max_steps: 1408
scene: 
  path: 11_2.task
  Tool:
    # tool_name: DoublePushers
    # qpos: [0.3, 0.1, 0.5, 0., 0., 0., 0.7, 0.1, 0.5, 0., 0., 0.]
    tool_name: Gripper
    qpos: [0.5, 0.15, 0.5, 0., 0., 0., 0.05]
    size: (0.02, 0.06, 0.02)
    friction: 1.
saver:
  path: examples/output/task11/stage3
trainer:
  nsteps: 1000
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp back end of the object '1' vertically without rotation
  equations: 
    - cgrasp(backpart(backpart(get_iobj('1'))))
  constraints:
    - 'collision_free'
    - 'minimize_dist'
optim:
  lr: 0.02
prog: 
  code: |

    obj0 = get_iobj('0')
    obj1 = get_iobj('1')
    goal0 = get_goal('0')
    goal1 = get_goal('1')

    tand(
      tkeep(no_break(obj0), .2),
      tkeep(no_break(obj1), .2),
      last(emd(obj0  , goal0  , 0.001), 1.),
      last(emd(obj1  , goal1  , 0.001), 1.),

      # last(away(obj1, 0.001, 0.2), 2.),
    )
  lang: Deform the object '0' and '1' into its goal shape.
  horizon: 70
