path: task11
final_goal: 11_3.task
common:
  trainer:
    nsteps: 300
stages:
  - config: stage2.yaml
    modifier:
      scene:
        goal: 11_2.task 
  - config: stage3.yaml
    modifier:
      scene:
        goal: 11_3.task