path: task8
final_goal: 8_4.task
common:
  trainer:
    nsteps: 300
stages:
  - config: stage1.yaml 
  - config: away.yaml
    modifier:
      scene:
        goal: 8_1.task 
      trainer:
        nsteps: 50
      prog:
        horizon: 20
  - config: stage2.yaml
    modifier:
      scene:
        goal: 8_2.task 
  - config: away.yaml
    modifier:
      scene:
        goal: 8_2.task 
      trainer:
        nsteps: 50
      prog:
        horizon: 20
  - config: stage3.yaml
    modifier:
      scene:
        goal: 8_3.task 
  - config: away.yaml
    modifier:
      scene:
        goal: 8_3.task 
      trainer:
        nsteps: 50
      prog:
        horizon: 20
  - config: stage4.yaml
    modifier:
      scene:
        goal: 8_4.task
  - config: away.yaml
    modifier:
      scene:
        goal: 8_4.task 
      trainer:
        nsteps: 50
      prog:
        horizon: 20