max_steps: 1408
scene: 
  path: 57_1.task
  Tool:
    # tool_name: DoublePushers
    # qpos: [0.3, 0.1, 0.5, 0., 0., 0., 0.7, 0.1, 0.5, 0., 0., 0.]
    tool_name: Gripper
    qpos: [0.5, 0.15, 0.5, 0., 0., 0., 0.05]
    size: (0.02, 0.06, 0.02)
    friction: 1.
saver:
  path: task57/stage2
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp the back end of the object 'rope' vertically without rotation
  equations: 
    - xyzgrasp(backend(get_iobj('rope')))
  constraints:
    - 'collision_free'
    - 'minimize_dist'
prog: 
  code: |
    obj = get('rope')
    tand(
      keep(no_break(obj)),
      last(emd2goal('rope')),
      last(emd2goal('salmon_ball')),
      last(emd2goal('black_ball')),
      tand(keep(touch(obj), end=0.6), last(away(obj)))
    )
  lang:
    "Deform the rope 'rope' into its goal shape and please do not break it."
  horizon: 70
