path: task57
final_goal: 57_4.task
common:
  trainer:
    nsteps: 500
stages:
  - config: stage1.yaml 
  - config: stage2.yaml
    modifier:
      scene:
        goal: 57_2.task 
  - config: stage3.yaml
    modifier:
      scene:
        goal: 57_3.task 
  - config: stage4.yaml
    modifier:
      scene:
        goal: 57_4.task