Shape:
  childs:
    - method: box
      center: (0.5, 0.08, 0.5)
      shape_args: (0.1, 0.1, 0.1)
      color: (0, 0, 255)
      yield_stress: 200.
Tool:
  tool_name: Gripper
  qpos: [0.5, 0.25, 0.5, 0., 0., 0., 0.1]
  mode: Capsule