Shape:
  childs:
    - method: box
      center: (0.5, 0.08, 0.5)
      shape_args: (0.15, 0.05, 0.15)
      color: (0, 0, 255)
      yield_stress: 30.
Tool:
  tool_name: Fingers
  size: (0.04, 0.15, 0.04)
  mode: Capsule