#Path: tester/windrope/1.th
Shape:
  childs:
    - method: cylinder
      center: (0.7, 0.13, 0.5)
      args: (0.03, 0.2)
      color: (255, 0, 0)

    - method: box
      center: (0.45, 0.06, 0.5)
      shape_args: (0.3, 0.03, 0.03)
      color: (0, 255, 0)
      nu: 0.1
      E: 1000
      yield_stress: 50
Tool:
  tool_name: Gripper
  qpos: [0.5, 0.05, 0.2, 0., 1.57, 0., 0.00]
  size: (0.03, 0.05, 0.3)