#Path: tester/windrope/1.th
Shape:
  childs:
    - method: cylinder
      center: (0.5, 0.1, 0.5)
      args: (0.05, 0.2)
      color: (255, 0, 0)

    - method: box
      center: (0.5, 0.05, 0.3)
      shape_args: (0.4, 0.02, 0.02)
      color: (0, 255, 0)
      nu: 0.1
      yield_stress: 30
#Tool:
#  tool_name: Gripper
#  qpos: [0.5, 0.05, 0.2, np.pi/4, 0.00]
#  size: (0.01, 0.03, 0.1)
Tool:
  tool_name: Pusher
  qpos: [0.5, 0.15, 0.15]
  mode: Capsule