max_steps: 1408
scene: 
  path: 13_0.task
  Tool:
    # tool_name: DoublePushers
    # qpos: [0.3, 0.1, 0.5, 0., 0., 0., 0.7, 0.1, 0.5, 0., 0., 0.]
    tool_name: Gripper
    qpos: [0.5, 0.15, 0.5, 0., 0., 0., 0.01]
    size: (0.02, 0.06, 0.02)
    friction: 10.
saver:
  path: examples/output/task13/stage1_gpt
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  equations: 
    - xyzgrasp(get_iobj('small1'))
  constraints:
    - 'collision_free'
    - 'minimize_dist'
prog: 
  code: ""
  lang: "
    There are 6 objects called 'small1', 'small2', 'small3', 'big1', 'big2', 'big3'. 
    Grasp the object 'small1' and move the object 'small1' to the goal place.
    Make sure other objects are keeping theirs place.
    Make sure small1 is keeping its shape.
    tkeep is better than tlast except using away.
    "
  max_retry: 10
  horizon: 70
