max_steps: 1408
scene: 
  path: 47_7.task
  Tool:
    tool_name: DoublePushers
    qpos: [0.3, 0.1, 0.5, 0., 0., 0., 0.7, 0.1, 0.5, 0., 0., 0.]
    size: (0.02, 0.2, 0.2)
saver:
  path: example/output/task47/stage8
trainer:
  nsteps: 300

tool_sampler:
  n_samples: 1000
  optimize_loss: true
  use_lang: true
  lang: "use the large fingers to manipulate all object vertically"
  equations:
    - grasp('all')
    - no_rotation()
  constraints:
    - collision_free
    - touch_pcd('all')
optim:
  lr: 0.02
prog: 
  code: |
    objs = get('all')
    goals = get_goal('all')
    tand(
      last(emd(objs, goals)),
      keep(touch(objs), end=0.6),
    )
  lang: 
    "
    Reshape the object all into their corresponding goal shapes.
    Touch the all.
    Away when task finished.
    Use emd not shape_match.
    tkeep is better than tlast except using away.
    "
  max_retry: 0
  horizon: 70