max_steps: 1700
scene: 
  path: 47_1.task
  Tool:
    tool_name: Gripper
    qpos: [0.5, 0.15, 0.5, 0., 0., 0., 0.01]
    size: (0.02, 0.03, 0.02)
    friction: 10.
saver:
  path: examples/output/task47/stage2
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  n_sol: 25

  use_lang: false
  lang: "grasp 'right_up' vertically"
  equations: 
    - vgrasp(get('right_up'))
  constraints:
    - 'collision_free'
    - 'minimize_dist'
prog: 
  code: |
    obj = get('right_up')
    goal = get_goal('right_up')
    other = get_others('right_up')

    tand(
      keep(fix_shape(obj)),
      keep(fix_place(other)),
      last(emd(obj, goal)),
      tand(keep(touch(obj), end=0.6), last(away(obj))),
    )

  lang: "
    Grasp the object 'right_up' and move the object 'right_up' to the goal place.
    Make sure other objects are keeping theirs place and move the tool away in the end.
  "
  horizon: 70
