max_steps: 1700
scene: 
  path: 48_1.task
  Tool:
    tool_name: Gripper
    qpos: [0.5, 0.15, 0.5, 0., 0., 0., 0.01]
    size: (0.02, 0.03, 0.02)
    friction: 10.
saver:
  path: examples/output/task47/stage3
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  motion_planner:
    max_iter: 10000
  n_samples: 1000
  optimize_loss: true
  n_sol: 25

  use_lang: false
  lang: "grasp 'Yellow' vertically"
  equations: 
    - locate(get('Yellow'), _width = 0)
    - vertical()
    - pitch(1.57)
  constraints:
    - collision_free
    - touch_pcd('Yellow')
prog: 
  code: |
    obj = get('Yellow')
    goal = get_goal('Yellow')
    other = get_others('Yellow')

    tand(
      keep(fix_shape(obj)),
      keep(fix_place(other)),
      last(emd(obj, goal)),
      tand(keep(touch(obj), end=0.6), last(away(obj))),
    )

  lang: "
    Grasp the object 'Yellow' and move the object 'Yellow' to the goal place.
    Make sure other objects are keeping theirs place and move the tool away in the end.
  "
  horizon: 70
