max_steps: 1408
scene: 
  path: 22_2.task
  Tool:
    # tool_name: DoublePushers
    # qpos: [0.3, 0.1, 0.5, 0., 0., 0., 0.7, 0.1, 0.5, 0., 0., 0.]
    tool_name: Gripper
    qpos: [0.5, 0.15, 0.5, 0., 0., 0., 0.05]
    size: (0.02, 0.06, 0.02)
    friction: 10.
saver:
  path: task22_stage3_2
trainer:
  nsteps: 300
tool_sampler:
  n_samples: 1000
  equations: 
    - grasp('rope4')
  constraints:
    - 'collision_free'
optim:
  lr: 0.02
prog: 
  code: |
    rope = get('rope4')
    goal = get_goal('rope4')
    other = get_others('rope4')

    tand(
      last(emd2goal('rope4')),
      keep(no_break(rope)),
      keep(fix_place(other)),
      keep(touch(rope)),
    )
  horizon: 70
