max_steps: 1700
scene: 
  path: 52_3.task
  Tool:
    tool_name: DoublePushers
    qpos: [0.3, 0.1, 0.5, 0., 0., 0., 0.7, 0.1, 0.5, 0., 0., 0.]
    size: (0.03, 0.2)
    mode: Capsule
    friction: 0.
saver:
  path: example/output/task52/stage4
trainer:
  nsteps: 300
tool_sampler:
  n_samples: 0
  lang: "use the large fingers to manipulate the object 'snow' vertically"
  equations:
    - grasp('snow')
    - vertical()
  constraints:
    - collision_free
    - touch_pcd('snow')
optim:
  lr: 0.02
prog: 
  code: |
    all = get('all')
    tand(
      last(emd2goal('all')),
      keep(touch(all), end=0.6),
      last(away(all))
    )
  lang:
    "We want to carve all of the shape into the goal shape.
    keep is better than last except using away.
    We want the tool away from object when the task was finished."
  horizon: 70

