max_steps: 1408
scene: 
  path: 42_3.task
  Tool:
    tool_name: Gripper
    qpos: [0.3, 0.1, 0.5, 0., 0., 0., 0.05]
    friction: 10.
saver:
  path: example/output/task42/stage4
trainer:
  nsteps: 300

tool_sampler:
  n_samples: 1000
  optimize_loss: true
  equations: 
    - vgrasp(frontpart(frontpart(frontpart(get_iobj('blue_rect')))))
  constraints:
    - 'collision_free'
    - 'minimize_dist'
optim:
  lr: 0.02
prog: 
  code: |
    objs = get('blue_rect')
    goals = get_goal('blue_rect')
    other = get_others('blue_rect')
    tand(
      keep(fix_shape(objs)),
      keep(fix_place(other)),
      last(emd(objs, goals)),
      tand(keep(touch(objs), end=0.6), last(away(objs))),
    )
  lang: "
    Reshape the object blue_rect into their corresponding goal shapes.
    Touch the blue_rect.
    Away when task finished.
    Use emd not shape_match.
    tkeep is better than tlast except using away.
    "
  max_retry: 3
  horizon: 70