max_steps: 1408
scene: 
  path: 4_3.task
  Tool:
    tool_name: Gripper
    qpos: [0.5, 0.15, 0.5, 0., 0., 0., 0.05]
    size: (0.02, 0.06, 0.04)
    friction: 10.
saver:
  path: examples/output/task4/stage2/
trainer:
  nsteps: 1000
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp the object 'red_ball' vertically without rotation
  equations: 
    - grasp('red_ball')
  constraints:
    - 'collision_free'
    - 'minimize_dist'
optim:
  lr: 0.02
prog: 
  code: |

    obj = get_iobj('red_ball')
    others = get_others('red_ball')

    tand(
      last(emd2goal('red_ball'), end = 0.8),
      keep(fix_place(others)),
      keep(touch(obj, 0.001), end = 0.6),
      last(away(obj)),
    )
  lang:
    "
    Move all the objects into their corresponding goal place.
    Keep the shape of all the objects.
    tkeep is better than tlast except using away.
    "
  horizon: 70
