max_steps: 1024
scene: 
  path: 4_0_3.task
  Tool:
    tool_name: Pusher
    qpos: [0.5, 0.25, 0.5, 0., 0., 0.]
    size: (0.01, 0.1, 0.2)
    friction: 1.
saver:
  path: examples/output/task4/stage1/
trainer:
  nsteps: 1000
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp the object 'white_cylinder' vertically without rotation
  equations: 
    - grasp('white_cylinder')
  constraints:
    - 'collision_free'
    - 'minimize_dist'
optim:
  lr: 0.02
prog: 
  code: |

    obj = get_iobj('white_cylinder')

    tand(
      last(emd_all(0.001)),
      keep(touch(obj, 0.001), end = 0.6),
      last(away(obj, 0.001, 0.2)),
    )
  lang:
    "
    Reshape all the objects into their corresponding goal shape.
    keep is better than last except using away.
    "
  horizon: 50
