max_steps: 1700
scene: 
  path: 15_2.task
  Tool:
    # tool_name: DoublePushers
    # qpos: [0.3, 0.1, 0.5, 0., 0., 0., 0.7, 0.1, 0.5, 0., 0., 0.]
    tool_name: Gripper
    qpos: [0.20345482230186462, 0.03278876096010208, 0.3172341585159302, 0.0, 1.3722137212753296, 0.0, 0.044611115008592606]
    size: (0.01, 0.03, 0.01)
    friction: 10.
saver:
  path: task15_stage3
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp the object 'red' vertically without rotation
  equations: 
    - xyzgrasp('red')
  constraints:
    - 'collision_free'
    - 'minimize_dist'
prog: 
  code: |

    obj = get('red')
    otherobj = get_others('red')

    tand(
      keep(fix_place(otherobj)),
      last(emd2goal('red')),
      keep(touch(obj)),
    )
  lang:
    "
    Pick and place the object 'red' into its goal place.
    Keep touching the object 'red' and do not move other objects.
    "
  horizon: 70
