max_steps: 1700
scene: 
  path: 48_3.task
  Tool:
    tool_name: Gripper
    qpos: [0.5, 0.15, 0.5, 0., 0., 0., 0.01]
    size: (0.02, 0.06, 0.06)
    friction: 10.
saver:
  path: examples/output/task48/stage5
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  n_sol: 25

  use_lang: false
  lang: "grasp 'Purple' vertically"
  equations: 
    - locate(get('Purple'), _width = 0)
    - vertical()
  constraints:
    - 'collision_free'
    - 'minimize_dist'
prog: 
  code: |
    obj = get('Purple')
    goal = get_goal('Purple')
    other = get('Green')

    tand(
      keep(fix_place(other)),
      last(emd2goal('Yellow')),
      last(emd(obj, goal)),
      keep(touch(obj), end=0.6),
    )

  lang: "
    Grasp the object 'Purple' and move the object 'Purple' to the goal place.
    Make sure other objects are keeping theirs place and move the tool away in the end.
  "
  horizon: 70
