max_steps: 1700
scene: 
  path: 64_4.task
  Tool:
    # tool_name: DoublePushers
    # qpos: [0.3, 0.1, 0.5, 0., 0., 0., 0.7, 0.1, 0.5, 0., 0., 0.]
    tool_name: Gripper
    qpos: [0.5, 0.15, 0.5, 0., 0., 0., 0.01]
    size: (0.02, 0.06, 0.02)
    friction: 10.
saver:
  path: examples/output/task64/stage5
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp the 'white_ball_1' vertically
  equations: 
    - xzgrasp(get_iobj('white_ball_1'))
  constraints:
    - collision_free
    - touch_pcd('white_ball_1')
prog: 
  code: |

    obj = get_iobj('white_ball_1')
    goal = get_goal('white_ball_1')
    otherobj = get_others('white_ball_1')

    tand(
      tkeep(fix_shape(obj), fix_shape_weight),
      tkeep(fix_shape(otherobj), fix_shape_weight),
      tkeep(fix_place(otherobj), fix_place_weight),

      tkeep(shape_l2(obj, goal, 0.001), weight = samll_object_weight),
      tkeep(touch_mean(obj, 0.001), touch_weight, 0., 0.6),
      last(away(obj, 0.001, 0.2), away_weight),
    )
  lang: "Manipulate all plasticine into goal directly."

  horizon: 70
