max_steps: 1408
scene: 
  path: 70_0.task
  Tool:
    # tool_name: DoublePushers
    # qpos: [0.3, 0.1, 0.5, 0., 0., 0., 0.7, 0.1, 0.5, 0., 0., 0.]
    tool_name: Pusher
    qpos: [0.5, 0.25, 0.5, 0., 0., 0.]
    size: (0.2, 0.04, 0.2)
    friction: 0.
saver:
  path: example/output/task70/stage1
trainer:
  nsteps: 300

tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: put the board above 'snow' vertically
  equations: 
    - grasp('snow')
    - isabove('snow')
    - vertical()
  constraints:
    - 'collision_free'
    - 'minimize_dist'
optim:
  lr: 0.02
prog: 
  code: |
    objs = get('snow')
    goals = get_goal('snow')
    tand(
      last(emd(objs, goals)),
      keep(touch(objs), end=0.6),
    )
  lang: "Manipulate snow plasticine into goal directly."
  max_retry: 3
  horizon: 70