max_steps: 1408
scene:
  path: 57_0.task
  Tool:
    tool_name: Gripper
    qpos:
    - 0.4939408302307129
    - 0.05598607286810875
    - 0.7466087937355042
    - 0.0
    - 0.0
    - 0.0
    - 0.05215955153107643
    size: (0.02, 0.06, 0.02)
    friction: 1.0
saver:
  path: task57_stage1
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp the back end of the object 'rope' vertically without rotation
  equations:
  - xyzgrasp(backpart(backpart(get_iobj('rope'))))
  constraints:
  - collision_free
  - minimize_dist
  code: |-
    - set_tool(gripper)
    - set_coord(backend('rope'), 'xyz')
    - isbehind('rope')
    - set_rot('?', 0., 0.)  # '?' represents a placeholder for not rotating in that axis
prog:
  code: |
    obj = get('rope')
    other = get_others('rope')
    tand(
      keep(no_break(obj)),
      last(emd(other, get_others_goals('rope'))),
      last(emd2goal('rope')),
      keep(touch(obj)),
    )
  lang: Deform the rope 'rope' into its goal shape and please do not break it.
  horizon: 70
  translator:
    code: |-
      tand(
        last(emd('rope', goal('rope'))),
        keep(touch('rope')),
        keep(no_break('rope'))
      )
