max_steps: 1024
scene:
  path: 38_0.task
  Tool:
    tool_name: Gripper
    qpos:
    - 0.5443501472473145
    - 0.05932264029979706
    - 0.3694576621055603
    - 0.0
    - 0.0
    - 1.5707963705062866
    - 0.0828433409333229
    size: (0.02, 0.06, 0.02)
    friction: 5.0
saver:
  path: task38_deform
trainer:
  nsteps: 1000
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp the front end of the object 'left' horizontally and rotate 90 degree.
  equations:
  - cgrasp(frontpart(get_iobj('left')))
  constraints:
  - collision_free
  - minimize_dist
  code: |-
    - set_tool(gripper)
    - set_coord(frontend('left'), 'xyz')
    - set_rot(0., 0., np.pi/2)
optim:
  lr: 0.02
prog:
  code: |2

    objs = get('all')
    tand(
      keep(no_break(objs)),
      keep(emd2goal('all')),
      last(away(objs)),
    )
  lang: ' Reshape all the objects into their corresponding goal shapes. Make sure
    they are not broken. '
  horizon: 50
  translator:
    code: |-
      tand(
        last(emd('all', goal('all'))),
        keep(touch('all')),
        keep(no_break('mid')),
        keep(no_break('left')),
        keep(no_break('right'))
      )
