max_steps: 1700
scene:
  path: 5_0_1.task
  Tool:
    tool_name: Gripper
    qpos:
    - 0.2730940878391266
    - 0.058373261243104935
    - 0.6100195050239563
    - 1.5707963705062866
    - 1.5707963705062866
    - 0.0
    - 0.03885454311966896
    size: (0.02, 0.06, 0.02)
    friction: 5.0
saver:
  path: task5_moveover
trainer:
  nsteps: 1000
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  equations:
  - set_coord(frontpart('top_right_mat'), 'xyz')
  - set_rot(np.pi/2, np.pi/2, 0.)
  constraints:
  - collision_free
  - minimize_dist
  lang: grasp the front end of the object 'top_right_mat' horizontally.
  code: |-
    - set_tool(gripper)
    - set_coord('brown', 'xyz')
    - set_rot(0., 0., 0.)
  motion_planner:
    max_iter:
      10000
prog:
  code: "\nobj0 = get('top_right_mat')\ngoal0 = get_goal('top_right_mat')\nother =\
    \ get_others('top_right_mat')\ntand(\n  keep(no_break(obj0)),\n  keep(fix_place(other)),\n\
    \  last(away(get('all'))),\n  last(emd(obj0, goal0, 0.001)), \n)\n"
  lang: Pick up the object 'brown'. First lift it above the other objects and then move it into the goal positions without moving the others.
  horizon: 80
  translator:
    code: |-
      tand(
        last(emd('brown', goal('brown'))),
        keep(touch('brown'), end=0.5),
        last(gt(py(com('brown')), py(max(pcd('white')))), end=0.5), 
        keep(fix_place(others('brown')))
      )