max_steps: 1700
scene:
  path: 37_0.task
  Tool:
    tool_name: Pusher
    qpos:
    - 0.5
    - 0.25
    - 0.5
    - 0.0
    - 0.0
    - 0.0
    size: (0.02, 0.1, 0.2)
    friction: 0.0
saver:
  path: task37_cut
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: put a knife above the object 'obj'
  equations:
  - grasp('obj')
  - no_rotation()
  constraints:
  - collision_free
  - minimize_dist
  code: |-
    - set_tool(knife)
    - set_coord('obj', 'xz')
    - isabove('obj')
    - set_rot(0., 0., 0.)
prog:
  code: |
    obj = get('obj')
    goal = get_goal('obj')

    tand(
        last(emd(obj, goal)),
        keep(touch(obj)),
    )
  lang: 'cut the object into the target shape. Cut down the left part of the object out.'
  horizon: 80
  translator:
    code: |-
      tand(
        last(emd('obj', goal('obj'))),
        keep(touch(leftpart('obj'))),
        keep(movedown()),
      )
