max_steps: 1700
scene:
  path: 10_0.task
  Tool:
    tool_name: Gripper
    qpos:
    - 0.2730940878391266
    - 0.058373261243104935
    - 0.6100195050239563
    - 1.5707963705062866
    - 1.5707963705062866
    - 0.0
    - 0.03885454311966896
    size: (0.02, 0.06, 0.02)
    friction: 5.0
saver:
  path: task10_stage1
trainer:
  nsteps: 1000
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  equations:
  - set_coord(frontpart('top_right_mat'), 'xyz')
  - set_rot(np.pi/2, np.pi/2, 0.)
  constraints:
  - collision_free
  - minimize_dist
  lang: grasp the front end of the object 'top_right_mat' horizontally.
  code: |-
    - set_tool(gripper)
    - set_coord(frontend('top_right_mat'), 'xyz')
    - set_rot(np.pi/2, np.pi/2, 0.)
prog:
  code: "\nobj0 = get('top_right_mat')\ngoal0 = get_goal('top_right_mat')\nother =\
    \ get_others('top_right_mat')\ntand(\n  keep(no_break(obj0)),\n  keep(fix_place(other)),\n\
    \  last(away(get('all'))),\n  last(emd(obj0, goal0, 0.001)), \n)\n"
  lang: Pick up the object 'top_right_mat' and place it into the goal position without
    breaking it. Please do not move other objects.
  horizon: 80
  translator:
    code: |-
      tand(
        last(emd('top_right_mat', goal('top_right_mat'))),
        keep(fix_place(others('top_right_mat'))),
        keep(no_break('top_right_mat')),
        keep(touch('top_right_mat'))
      )
