max_steps: 1408
scene:
  path: 2_0_2.task
  Tool:
    tool_name: Gripper
    qpos:
    - 0.5
    - 0.2
    - 0.5
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    size: (0.02, 0.06, 0.02)
    friction: 1.0
saver:
  path: task2_wind
trainer:
  nsteps: 300
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp the back end of the object 'blue' horizontally
  equations:
  - cgrasp(backpart(backpart(get_iobj('blue'))))
  constraints:
  - collision_free
  - minimize_dist
  code: |-
    - set_tool(gripper)
    - set_coord(backend('blue'), 'xyz')
    - set_rot(0., 0., np.pi/2)
optim:
  lr: 0.02
prog:
  code: |
    obj = get('blue')
    tand(
      keep(no_break(obj)),
      last(emd2goal('all')),
      keep(touch(obj))
    )
  lang: Deform the rope 'blue' into its goal shape and please do not break it.
  horizon: 70
  translator:
    code: |-
      tand(
        last(emd('blue', goal('blue'))),
        keep(touch('blue')),
        keep(no_break('blue'))
      )
