max_steps: 1700
scene:
  path: 18_3.task
  Tool:
    tool_name: Gripper
    qpos:
    - 0.4898988902568817
    - 0.046875
    - 0.4107566177845001
    - 0.0
    - 0.0
    - 1.5707963705062866
    - 0.00036793036269955337
    size: (0.02, 0.06, 0.02)
    friction: 10.0
saver:
  path: task18
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp the front left part of the "bottom_left_mat" horizontally
  equations:
  - cgrasp(frontpart(leftpart('bottom_left_mat')))
  constraints:
  - collision_free
  - minimize_dist
  code: |-
    - set_tool(gripper)
    - set_coord(frontpart(leftpart('bottom_left_mat')), 'xyz')
    - set_rot(0., 0., np.pi/2)
prog:
  code: |2

    obj = get('bottom_left_mat')
    otherobj = get_others('bottom_left_mat')

    tand(
      keep(fix_place(otherobj)),
      last(emd2goal('bottom_left_mat')),
      keep(touch(obj)),
    )
  lang: ' Pick and place the object ''bottom_left_mat'' into its goal place. Keep
    touching the object ''bottom_left_mat'' and do not move other objects. '
  horizon: 70
  translator:
    code: |-
      tand(
        last(emd('bottom_left_mat', goal('bottom_left_mat'))),
        keep(touch('bottom_left_mat')),
        keep(fix_place(others('bottom_left_mat')))
      )
