max_steps: 1408
scene: 
  path: 2_0_2.task
  Tool:
    tool_name: Gripper
    qpos: [0.5, 0.15, 0.5, 0., 0., 0., 0.05]
    size: (0.02, 0.06, 0.02)
    friction: 1.
saver:
  path: task2_wind
trainer:
  nsteps: 300
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: grasp the back end of the object 'blue' vertically without rotation
  equations: 
    - cgrasp(frontpart(frontpart('blue')))
  constraints:
    - 'collision_free'
    - 'minimize_dist'
optim:
  lr: 0.02
prog: 
  code: |
    obj = get('blue')
    tand(
      keep(no_break(obj)),
      last(emd2goal('all')),
      tand(keep(touch(obj), end=0.6), last(away(obj)))
    )
  lang:
    "
    Reshape all the objects into their corresponding goal shapes.
    Make sure all the object is not break.
    Use emd not shape_match.
    tkeep is better than tlast except using away.
    "
  horizon: 70
