max_steps: 1700
scene: 
  path: 63_3.task
  Tool:
    tool_name: Gripper
    qpos: [0.2844, 0.0598, 0.7059, 0.0000, 0.0000, 0.0000, 0.1601]
    size: (0.02, 0.2, 0.06)
    friction: 10.
saver:
  path: task63_stage4
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  n_sol: 25

  use_lang: True
  lang: "grasp 'white_rope' vertically"
  equations: 
    - vgrasp(get_iobj('white_rope'))
  constraints:
    - collision_free
    - touch_pcd('white_rope')
prog: 
  code: |
    obj = get('white_rope')
    goal = get_goal('white_rope')
    other = get_others('white_rope')

    tand(
      keep(fix_shape(obj)),
      keep(fix_place(other)),
      last(emd(obj, goal)),
      tand(keep(touch(obj), end=0.6), last(away(obj))),
    )

  lang: "
    Grasp the object 'white_rope' and move the object 'white_rope' to the goal place.
    Make sure other objects are keeping theirs place and move the tool away in the end.
  "
  horizon: 70
