path: task10
final_goal: 10_2.task
common:
  trainer:
    nsteps: 300
stages:
  - config: stage1.yml 
  - config: away.yaml
    modifier:
      scene:
        goal: 10_1.task 
  - config: stage2.yaml
    modifier:
      scene:
        goal: 10_2.task
  - config: away.yaml
    modifier:
      scene:
        goal: 10_2.task 