max_steps: 1700
scene: 
  path: 72_3.task
  Tool:
    tool_name: Gripper
    qpos: [0.7, 0.07, 0.7, 0., 0., 1.57, 0.05]
    size: (0.02, 0.06, 0.02)
    friction: 5.
saver:
  path: examples/output/task72/stage4
trainer:
  nsteps: 1000
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  n_sol: 25

  use_lang: True
  lang: "grasp 'yellow_small' vertically"
  equations: 
    - cgrasp(get_iobj('yellow_small'))
  constraints:
    - 'collision_free'
    - 'minimize_dist'
prog: 
  code: |

    obj = get('yellow_small')
    goal = get_goal('yellow_small')
    other = get_others('yellow_small')

    tand(
      keep(fix_shape(obj)),
      keep(fix_place(other)),
      last(emd(obj, goal)),
      tand(keep(touch(obj), end=0.6), last(away(obj))),
    )
  lang: "
    Grasp the object 'yellow_small' and move the object 'yellow_small' to the goal place.
    Make sure other objects are keeping theirs place and move the tool away in the end.
  "
  horizon: 80
