max_steps: 1700
scene: 
  path: 59_0.task
  Tool:
    tool_name: Gripper
    qpos: [0.2844, 0.0598, 0.7059, 0.0000, 0.0000, 0.0000, 0.1601]
    size: (0.02, 0.06, 0.02)
    friction: 10.
saver:
  path: task59_stage1
trainer:
  nsteps: 300
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  n_sol: 25

  use_lang: True
  lang: "grasp red_ball vertically"
  equations: 
    - xyzgrasp(get_iobj('red_ball'))
  constraints:
    - 'collision_free'
    - 'minimize_dist'
prog: 
  code: |
    obj = get('red_ball')
    goal = get_goal('red_ball')
    other = get_others('red_ball')

    tand(
      keep(fix_shape(obj)),
      keep(fix_place(other)),
      last(emd(obj, goal)),
      tand(keep(touch(obj), end=0.6), last(away(obj))),
    )

  lang: "
    Grasp the object 'red_ball' and move the object 'red_ball' to the goal place.
    Make sure other objects are keeping theirs place and move the tool away in the end.
  "
  horizon: 70
