path: task60
final_goal: 60_3.task
common:
  trainer:
    nsteps: 500
stages:
  - config: stage1.yaml 
  - config: away.yaml
    modifier:
      scene:
        goal: 60_1.task 
  - config: stage2.yaml
    modifier:
      scene:
        goal: 60_2.task 
  - config: away.yaml
    modifier:
      scene:
        goal: 60_2.task 
  - config: stage3.yaml
    modifier:
      scene:
        goal: 60_3.task 
  - config: away.yaml
    modifier:
      scene:
        goal: 60_3.task 