max_steps: 1700
scene: 
  path: 54_3.task
  Tool:
    tool_name: Pusher
    qpos: [0.5, 0.25, 0.5, 0., 0., 0.]
    size: (0.01, 0.1, 0.2)
    friction: 1.
saver:
  path: example/output/task54/stage4
trainer:
  nsteps: 1000
optim:
  lr: 0.02
tool_sampler:
  n_samples: 1000
  optimize_loss: true
  lang: cut snow vertically and do not rotate it 
  equations: 
    - grasp('snow')
    - no_rotation()
  constraints:
    - 'collision_free'
    - 'minimize_dist'
prog: 
  code: |
    obj = get('snow')
    goal = get_goal('snow')

    tand(
        last(emd(obj, goal)),
        keep(touch(obj, 0.001)),
    )
  lang:
    "
    You should cut the object into goal shape and move the tool away in the end.
    "
  horizon: 80
